// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asflhdkchmggbgdqeowh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZmxoZGtjaG1nZ2JnZHFlb3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU3MzU4NTgsImV4cCI6MjA4MTMxMTg1OH0.jLSAjUzOMKzdMZK4fnyBg0No_hxSq2GEBCGhMUKTR7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);