// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmnipfpvlsulhotfgacr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptbmlwZnB2bHN1bGhvdGZnYWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzMyOTcsImV4cCI6MjA2NDc0OTI5N30.qKpUP_nLY8uawypTeHH_3wSqVxPXGfhrQJcbRkXrU6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);